version: "3"

services:

  php-server:
    container_name: utep-php-server
    image: php:utep
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysqlDB #172.17.0.2 #AUTOMATE
    depends_on:
      - mysqlDB
    ports:
      - "8080:80"
   
  mysqlDB:
    container_name: utep-mysql-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: s20am_team10
    
