version: "3"

services:

  php-server:
    container_name: utep-php-server
    image: php:utep
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysqlDB
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: s20am_team10
    depends_on:
      - mysqlDB
    ports:
      - "8080:80"

  mysqlDB:
    container_name: utep-mysql-db
    image: mysql:s20am_team10
    build:
      context: assignments/.
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: s20am_team10
