version: "3"

services:

  php-server:
    container_name: php-server
    image: php:utep
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  mysqlDB:
    container_name: php-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: utep
      MYSQL_USER: user
      MYSQL_PASSWORD: utep
      MYSQL_DATABASE: utep