version: "3"

services:

  php-server:
    container_name: php-server
    image: php:utep
    build:
      context: public/.
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: 172.18.0.2 #AUTOMATE
    depends_on:
      - mysqlDB
    ports:
      - "8080:80"

  mysqlDB:
    container_name: php-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: utep
      MYSQL_USER: user
      MYSQL_PASSWORD: utep
      MYSQL_DATABASE: s20am_team10
