apiVersion: apps/v1

kind: Deployment

metadata:
  name: utep-php
  labels:
    tier: frontend
    course: database
    app: utep-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utep-php
  template:
    metadata:
      labels:
        app: utep-php
    spec:
      containers:
        - name: utep-php
          image: manguilar22/php:utep
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: mysql-utep-svc
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: s20am_team10
---
apiVersion: v1
kind: Service
metadata:
  name: utep-php-svc
  labels:
    app: utep-php
spec:
  type: NodePort
  selector:
    app: utep-php
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000